apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: my-operators-namespace
  name: my-operator-role
rules:
- apiGroups:
  - operator.sample.com
  resources:
  - “*”
  verbs:
  - “*”
- apiGroups:
  - “”
  resources:
  - pods
  verbs:
  - get
  - watch
  - list
